### ISSUE TITLE
setblock error

### ISSUE THREAD

**Issue by johnelder** [BoomerBR/ConsoleScheduler#1]
Running Spigot 1.9.2.

Scheduling a setblock command gives the following error:

`java.lang.IllegalStateException: Asynchronous block remove!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.9.2.jar:git-Spigot-1480adb-f92e01b]
        at net.minecraft.server.v1_9_R1.Block.remove(Block.java:282) ~[spigot-1.9.2.jar:git-Spigot-1480adb-f92e01b]
        at net.minecraft.server.v1_9_R1.Chunk.a(Chunk.java:468) ~[spigot-1.9.2.jar:git-Spigot-1480adb-f92e01b]
        at net.minecraft.server.v1_9_R1.World.setTypeAndData(World.java:365) ~[spigot-1.9.2.jar:git-Spigot-1480adb-f92e01b]
        at net.minecraft.server.v1_9_R1.CommandSetBlock.execute(SourceFile:95) ~[spigot-1.9.2.jar:git-Spigot-1480adb-f92e01b]
        at org.bukkit.craftbukkit.v1_9_R1.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:108) [spigot-1.9.2.jar:git-Spigot-1480adb-f92e01b]
        at org.bukkit.craftbukkit.v1_9_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:43) [spigot-1.9.2.jar:git-Spigot-1480adb-f92e01b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9.2.jar:git-Spigot-1480adb-f92e01b]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9.2.jar:git-Spigot-1480adb-f92e01b]
        at BoomerBR.Plugin.ConsoleScheduler.runCommand(ConsoleScheduler.java:138) [ConsoleScheduler.jar:?]
        at BoomerBR.Plugin.ConsoleScheduler$2.run(ConsoleScheduler.java:110) [ConsoleScheduler.jar:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.9.2.jar:git-Spigot-1480adb-f92e01b]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-1.9.2.jar:git-Spigot-1480adb-f92e01b]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
`

Any ideas?

Thanks,
John

**Comment by BoomerBR** [comment]
What command you are trying to run?

**Comment by BoomerBR** [comment]
Due to inactivity issue closed.
